version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=
      - DB_NAME=
      - DB_USER=
      - DB_PASS=
      - DB_PORT=
    depends_on:
      - db
    links:
      - db
  db:
    image: "postgres"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - 5434:5434
    command: -p 5434
