# Generated by Django 4.1.7 on 2023-03-19 10:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=300)),
                ('address2', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('isocountry', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('instructions', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=300)),
                ('address2', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('isocountry', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('instructions', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('printertype', models.CharField(choices=[('zpl', 'zpl'), ('Zebra', 'Zebra')], default='Zebra', max_length=400)),
                ('weight', models.FloatField(default=0.0)),
                ('externalUnitId', models.CharField(default='', max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.CharField(max_length=100)),
                ('shipmentReference', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('pickupDate', models.DateField(max_length=100)),
                ('item', models.DateField(max_length=100)),
                ('unitNumber', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('trackingId', models.CharField(default='', max_length=80, null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_receiver', to='core.receiver')),
            ],
        ),
    ]
