# Generated by Django 4.1.7 on 2023-03-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
