# Generated by Django 4.1.7 on 2023-03-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_label_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_receiver', to='core.receiver'),
        ),
        migrations.AlterField(
            model_name='label',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_sender', to='core.sender'),
        ),
    ]
