# Generated by Django 4.1.7 on 2023-03-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_label_receiver_alter_label_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='sender',
        ),
        migrations.AddField(
            model_name='receiver',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_receiver', to='core.label'),
        ),
    ]
