# Generated by Django 4.1.7 on 2023-03-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_label_sender_receiver_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='label',
        ),
        migrations.AddField(
            model_name='label',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_sender', to='core.sender'),
        ),
    ]
